//! UI components for clipboard history.
//!
//! This module provides GPUI views and components for the clipboard history feature,
//! including the main list view, item rendering, search, and clipboard actions.

mod actions;
mod clipboard_item;
mod clipboard_view;

pub use clipboard_item::{ClipboardItemView, HighlightedText};
pub use clipboard_view::ClipboardHistoryView;

// GPUI actions (unit structs generated by the actions! macro)
pub use actions::{
    ClearClipboardHistory, CloseClipboardHistory, CopyClipboardItem, DeleteClipboardItem,
    OpenClipboardHistory, PasteAndDontSave, PasteAsPlainText, PasteClipboardItem,
    RefreshClipboardHistory, SelectNextClipboardItem, SelectPreviousClipboardItem,
    ShowClipboardActions, TogglePinClipboardItem,
};

// Request structs for actions that need parameters
pub use actions::{
    CopyClipboardItemRequest, DeleteClipboardItemRequest, PasteClipboardItemRequest,
    PinClipboardItemRequest, SearchClipboardHistoryRequest, UnpinClipboardItemRequest,
};
